services:
  bracedpy_server:
    container_name: bracedpy_server
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: '${SERVER_PORT}'
      ALLOWED_HOSTS: '${ALLOWED_HOSTS}'
    volumes:
      - ./compiler:/app/compiler
  
  bracedpy_client:
    container_name: bracedpy_client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    environment:
      NGINX_PORT: '${NGINX_PORT}'
      SERVER_URL: '${VITE_SERVER_URL}'

  bracedpy_compiler:
    container_name: bracedpy_compiler
    build:
      context: ./compiler
      dockerfile: Dockerfile
    volumes:
      - ./compiler:/app/compiler
